var dir_62d04610ab7eeb16116e00faf518798d =
[
    [ "AxisBucketNaming.cs", "AxisBucketNaming_8cs.html", "AxisBucketNaming_8cs" ],
    [ "AxisSlot.cs", "AxisSlot_8cs.html", "AxisSlot_8cs" ],
    [ "AxisSlotInfo.cs", "AxisSlotInfo_8cs.html", "AxisSlotInfo_8cs" ],
    [ "BalloonTypeCount.cs", "BalloonTypeCount_8cs.html", "BalloonTypeCount_8cs" ],
    [ "ColorCount.cs", "ColorCount_8cs.html", "ColorCount_8cs" ],
    [ "CompositeTelemetrySink.cs", "CompositeTelemetrySink_8cs.html", "CompositeTelemetrySink_8cs" ],
    [ "FoldRule.cs", "FoldRule_8cs.html", "FoldRule_8cs" ],
    [ "GameplayMetricsService.cs", "GameplayMetricsService_8cs.html", "GameplayMetricsService_8cs" ],
    [ "ILevelMetricsView.cs", "ILevelMetricsView_8cs.html", "ILevelMetricsView_8cs" ],
    [ "IReadOnlyMetricSet.cs", "IReadOnlyMetricSet_8cs.html", "IReadOnlyMetricSet_8cs" ],
    [ "ISealedMetrics.cs", "ISealedMetrics_8cs.html", "ISealedMetrics_8cs" ],
    [ "ITelemetrySink.cs", "ITelemetrySink_8cs.html", "ITelemetrySink_8cs" ],
    [ "ItemActivationCount.cs", "ItemActivationCount_8cs.html", "ItemActivationCount_8cs" ],
    [ "JsonLinesTelemetrySink.cs", "JsonLinesTelemetrySink_8cs.html", null ],
    [ "LevelMetricsSnapshot.cs", "LevelMetricsSnapshot_8cs.html", "LevelMetricsSnapshot_8cs" ],
    [ "MetricAxis.cs", "MetricAxis_8cs.html", "MetricAxis_8cs" ],
    [ "MetricCatalog.cs", "MetricCatalog_8cs.html", "MetricCatalog_8cs" ],
    [ "MetricId.cs", "MetricId_8cs.html", "MetricId_8cs" ],
    [ "MetricScope.cs", "MetricScope_8cs.html", "MetricScope_8cs" ],
    [ "MetricScopeKind.cs", "MetricScopeKind_8cs.html", "MetricScopeKind_8cs" ],
    [ "MetricScopeState.cs", "MetricScopeState_8cs.html", "MetricScopeState_8cs" ],
    [ "MetricSet.cs", "MetricSet_8cs.html", "MetricSet_8cs" ],
    [ "MetricsSnapshotBase.cs", "MetricsSnapshotBase_8cs.html", "MetricsSnapshotBase_8cs" ],
    [ "RecordKind.cs", "RecordKind_8cs.html", "RecordKind_8cs" ],
    [ "RunMetricsSnapshot.cs", "RunMetricsSnapshot_8cs.html", "RunMetricsSnapshot_8cs" ],
    [ "SessionTelemetryContext.cs", "SessionTelemetryContext_8cs.html", "SessionTelemetryContext_8cs" ],
    [ "TelemetryEnvelope.cs", "TelemetryEnvelope_8cs.html", "TelemetryEnvelope_8cs" ],
    [ "TelemetryEnvelopeSerializer.cs", "TelemetryEnvelopeSerializer_8cs.html", "TelemetryEnvelopeSerializer_8cs" ],
    [ "TelemetrySinkBase.cs", "TelemetrySinkBase_8cs.html", "TelemetrySinkBase_8cs" ],
    [ "TelemetryStopwatch.cs", "TelemetryStopwatch_8cs.html", "TelemetryStopwatch_8cs" ],
    [ "TimerCatalog.cs", "TimerCatalog_8cs.html", "TimerCatalog_8cs" ],
    [ "TimerId.cs", "TimerId_8cs.html", "TimerId_8cs" ]
];